FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY target/tribetalk-0.0.1-SNAPSHOT.jar tribetalk.jar
EXPOSE 8080
#ENV SPRING_PROFILES_ACTIVE=prod
ENTRYPOINT ["java", "-jar", "tribetalk.jar"]
ENTRYPOINT ["java", "-jar", "tribetalk.jar"]