spring.application.name=ChatService
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/tribetalknosqldb?authSource=admin}
spring.data.mongodb.database=tribetalknosqldb
server.port=8081
# Kafka Producer Configuration
spring.kafka.producer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=when-authorized
management.health.defaults.enabled=true
