spring.application.name=tribetalk
server.port=8080

!spring.security.user.name=admin
!spring.security.user.password=password

spring.datasource.url=jdbc:h2:mem:tribetalkdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.org.springframework.security=DEBUG
jwt.secret=change_this_to_a_long_random_secret_with_min_256_bits
jwt.expirationMillis=3600000

