DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       displayname varchar(40) NOT NULL
);

CREATE TABLE authorities (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             authority VARCHAR(255) NOT NULL,
                             user_id BIGINT,
                             CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
