apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
  labels:
    app: chatservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
        version: v1
    spec:
      serviceAccountName: tribetalk-sa
      containers:
      - name: chatservice
        image: 430006376054.dkr.ecr.eu-north-1.amazonaws.com/chatservice:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SPRING_APPLICATION_NAME
          value: "ChatService"
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tribetalk-database-secrets
              key: mongodb_uri
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: tribetalk-app-secrets
              key: kafka_bootstrap_servers
        - name: SERVER_PORT
          value: "8081"
        resources:
          requests:
            memory: "384Mi"
            cpu: "200m"
          limits:
            memory: "768Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chatservice
  labels:
    app: chatservice
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: chatservice
