[databases]
mongodb ansible_host=10.0.10.161 ansible_user=ubuntu
postgresql ansible_host=10.0.10.178 ansible_user=ubuntu
redis ansible_host=10.0.10.49 ansible_user=ubuntu

[kafka]
kafka1 ansible_host=10.0.10.205 ansible_user=ubuntu

[bastion]
bastion ansible_host=13.61.144.161 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=~/.ssh/k8-SecurityKey.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/k8-SecurityKey.pem -o StrictHostKeyChecking=no ubuntu@13.61.144.161"'

[databases:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/k8-SecurityKey.pem -o StrictHostKeyChecking=no ubuntu@13.61.144.161"'

[kafka:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/k8-SecurityKey.pem -o StrictHostKeyChecking=no ubuntu@13.61.144.161"'
